site_name: Mosaic
repo_url: https://github.com/monstar-lab-oss/android-mosaic


extra_css:
  - stylesheets/extra.css
theme:
  logo: assets/logo.png
  favicon: assets/favicon.ico

  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.path
    - navigation.sections
    - navigation.sections.expand
  name: material
  palette:
    primary: custom
    accent: custom

nav:
  - 'API': api/
  - 'Changelog': changelog.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences