name: Publish Or Preview Documentation
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  pull-requests: write
  contents: write
  issues: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: |
          chmod +x ./generate_docs.sh
          ./generate_docs.sh
      - run: pip install mkdocs-material
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
        if: github.ref == 'refs/heads/main'
      - name: Deploy PR Preview
        run: |
          git checkout -b pr-${{ github.event.pull_request.number }}
          mkdocs gh-deploy --force
        if: github.event_name == 'pull_request'
      - name: Add PR Comment
        uses: mshick/add-pr-comment@v2.8.2
        if: github.event_name == 'pull_request'
        with:
          message: |
            Preview available at: ${{ steps.deploy.outputs.url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
